### ISSUE TITLE
SwerveDrivePoseEstimator simplification/optimization

### ISSUE THREAD

**Issue by HarryXChen3** [TechnoTitans/TitanWare2024#10]
According to the latest software post from mechanical advantage, theres a still [open PR](https://github.com/wpilibsuite/allwpilib/pull/5473) to wpilib that changes how the `SwerveDrivePoseEstimator` functions, simplifying the logic related to having to replay the odometry updates after applying a vision update.

Does this produce more desirable results and is it something we should incorporate in the time-being while the PR is still waiting to be merged/completed? Is it worth it to make a custom pose estimator considering the benefits and drawbacks - the current `SwerveDrivePoseEstimator` still works and isn't causing us any issues, but would this be better to the point where it would outweigh the extra work and cost to maintain?

> This year we record a buffer of all recent odometry poses instead of twists. We then find the difference between the vision and odometry pose and apply that Twist to our estimated pose. This logic was implemented in [our code](https://github.com/Mechanical-Advantage/RobotCode2024/blob/1aabdb77cfec23e7749a5982257751a2cb85a936/src/main/java/frc/robot/RobotState.java#L78-L126) based on this pull request [here](https://github.com/jlmcmchl/allwpilib/blob/bb6a7f487068c6ee1660da2bd1b0e562360c0c0e/wpimath/src/main/java/edu/wpi/first/math/estimator/PoseEstimator.java#L155-L193).

**Comment by MqxS** [comment]
WPILIB implemented
