### ISSUE TITLE
Logs folder is made on real robot despite all paths being set to log elsewhere

### ISSUE THREAD

**Issue by HarryXChen3** [TechnoTitans/TitanWare2024#22]
A folder is made (if it does not exist) at runtime/startup of the robot program at `/U/logs` (real robot) despite attempts to relocate logs into other folders, there should be no paths that point at `/U/logs` and thus the folder should not be created.

The folder is not actually written to (no files are ever written into the folder), but, weirdly enough, it *is* created if it does not exist (afaik, every time).

**Comment by HarryXChen3** [comment]
I looked into this briefly a little while ago and couldn't find anything wrong, its possible this is a bug on CTRE's side and not ours, but I want to be absolutely sure that we're not just doing something stupid.

**Comment by MqxS** [comment]
Ben opened internal report. He said it might be a bug on their end.

**Comment by MqxS** [comment]
![image](https://github.com/TechnoTitans/TitanWare2024/assets/34967410/b3c2fde6-2668-4a61-bd97-230e7e48d509)

**Comment by MqxS** [comment]
Not an issue anymore because we log everything in this logs folder now.
