### ISSUE TITLE
Fix swerve coast/brake mode on disabled vs. teleoperated control.

### ISSUE THREAD

**Issue by HarryXChen3** [TechnoTitans/TitanWare2024#44]
Something weird was happening with enabling brake mode on disable today. The robot should be in brake when disabled such that the robot stops ASAP when disabling instead of coasting further.

**Comment by MqxS** [comment]
Why can't we just leave them in brake?

![image](https://github.com/TechnoTitans/TitanWare2024/assets/34967410/25494f3b-5ec3-4e09-bff8-233c578ddf78)
![image](https://github.com/TechnoTitans/TitanWare2024/assets/34967410/1709710b-5d5e-4ea5-8249-79735921559e)
![image](https://github.com/TechnoTitans/TitanWare2024/assets/34967410/679bd626-0ad2-4f2f-999f-072edbcc9493)
