### ISSUE TITLE
Refactor and fix `GyroUtils`

### ISSUE THREAD

**Issue by HarryXChen3** [TechnoTitans/TitanWare2024#70]
`GyroUtils` in `frc.robot.utils.gyro` is a mess and has redundant methods for random things (which can probably just be removed). Also `robotPose2dToPose3dWithGyro` doesn't work properly as it seems to rotate the robot pose in an incorrect axes for the rotation.

Not sure if the entire class can be wiped, but its possible.

**Comment by MqxS** [comment]
Maybe fixed. needs to be tested
