### ISSUE TITLE
Project structure changes?

### ISSUE THREAD

**Issue by HarryXChen3** [TechnoTitans/TitanWare2024#9]
Mechanical advantage [talks about](https://www.chiefdelphi.com/t/frc-6328-mechanical-advantage-2024-build-thread/442736/179?u=harryxchen) a change in their "main principle for designing commands" from "commands running complex loops" to "only scheduling changes in the current state of each subsystem". I'm not sure what this means specifically, but I think its mainly about using state-machines to keep commands and command sequences less complex.

Maybe this deserves some thought? Is this already something we were going to implement?

> Project Structure
This season we are adopting a similar pattern to teams like 254, 1678, 5940, etc. for controlling our drive and other subsystems. Though we are still leveraging the subsystem and command classes in wpilib, our main principle for designing commands this year has changed from commands running complex loops to only scheduling changes in the current state of each subsystem. The advantages to this pattern are that writing complex autos is very readable and easy to do in code and all control code for each subsystem would be confined within itself.

**Comment by MqxS** [comment]
@HarryXChen3 What would an example of this be? Would this mean that you have commands that are just states like intake.intake() and intake.outtake() or would you just have your intake.setState() which takes in an enum.

Also, what would an example of a complex loop be?

**Comment by MqxS** [comment]
Do we already do this?

**Comment by HarryXChen3** [comment]
I think what we have now is fine. This issue was really only relevant before we decided on what structure to adopt and now that we already have one that seems to work fine? (and I'd argue is pretty decent actually) this doesn't make sense anymore.

And tbh, we kinda do this already anyway.
